development:
  adapter: postgresql
  encoding: unicode
  database: pg_development
  username: rails_user
  password: password
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: pg_development
  username: rails_user
  password: password
  pool: 5
  timeout: 5000